### ISSUE TITLE
Lua 52

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/lua-feedstock#1]
@alexbw you have to submit the recipe for Lua 5.2 to the branch you created. Once merge the build will be uploaded the same way the master builds are.

xref: https://github.com/conda-forge/staged-recipes/pull/230#issuecomment-219459760

**Comment by alexbw** [comment]
The recipe is submitted in the branch. If I merge it, it will overwrite the Lua 5.1 version, though. Don't we want a permanent record of each version?

**Comment by ocefpaf** [comment]
@alexbw your PR should point to the branch and not master.You are correct, you cannot merge and overwrite the current version. I have limited access now. Let me check how you created the branch I will get back to you soon.

**Comment by jakirkham** [comment]
You might also want a `5.1` branch added where `master` is now. Also, we have generally kept `master` as latest. So, after you create all of these branches feel free to move it up. to the latest version.

**Comment by alexbw** [comment]
Good idea, updated.

**Comment by jakirkham** [comment]
Just FYI, when you do make these PRs for different versions, please make sure to make a fork of this and add your changes to your fork. Only then PR them back here to the respective branches. Changes made to this repo are automatically deployed.

**Comment by alexbw** [comment]
Ok, got it.

**Comment by pelson** [comment]
This is looking good. Unless you are planning on adding others, you may wish to move the `5.2` branch to `master`. Then again, you may not 😄  - that is the beauty of conda-forge being a decentralised - you can make the call on how the branching is done.

**Comment by alexbw** [comment]
I'd like to maintain separate branches for each of 5.1, 5.2 and 5.3, but
I'm still not sure how to trigger a build on the non-master branches.

**Comment by jakirkham** [comment]
BTW it appears Lua 5.2 is failing on Travis CI.

**Comment by alexbw** [comment]
@jakirkham Where do I check that? The badges all seem to point to master

**Comment by jakirkham** [comment]
Please take a look at the [branches page]( https://github.com/conda-forge/lua-feedstock/branches ).

**Comment by jakirkham** [comment]
Guessing the recipe needs something like [this]( https://github.com/conda-forge/primesieve-feedstock/blob/23cb89db39d4fdf5fcb3809429ceed9de11440b4/recipe/build.sh ). Basically, the problem is `conda-build` hasn't done its rpath changes with `install_name_tool` yet so we need to point out where it needs to look for libraries.

**Comment by jakirkham** [comment]
In particular, please take a look at the `LIBRARY_SEARCH_VAR` portions.

**Comment by ocefpaf** [comment]
I believe this was done.

**Comment by jakirkham** [comment]
Sort of. We were still trying to sort out the OS X failure.

**Comment by jakirkham** [comment]
Though that probably could use a new issue. See issue ( https://github.com/conda-forge/lua-feedstock/issues/5 ) for the OS X build failure.
